### ISSUE TITLE
Doesn't build Revanced APKs, only vanced-microg

### ISSUE THREAD

**Issue by HulkSmashBurgers** [n0k0m3/revanced-build-template#108]
I used the template, modified build.targets so that only YOUTUBE_NONROOT and YTMUSIC_NONROOT are true. When I run ReVanced Build the only thing it builds is vanced-microg.
![ghrevanced](https://github.com/n0k0m3/revanced-build-template/assets/2564116/40c8bca9-200d-4019-984a-3ce00bf3d393)

**Comment by Serph91P** [comment]
found the error, my guess would be that ehe cli parameters got changed and the script is not updated to this:

```
Building YouTube Non-root APK
************************************
Unknown options: '-m', 'revanced-integrations.apk', '-b', 'revanced-patches.jar', '-a', 'com.google.android.youtube.apk', '-o', 'build/revanced-youtube-18.45.41.apk'
vanced-cli [-hV] [COMMAND]
Command line application to use ReVanced.
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  list-patches  List patches from supplied patch bundles.
  patch         Patch an APK file.
  options       Generate options file from patches.
  utility       Commands for utility purposes

**Comment by Serph91P** [comment]
fixed it but getting some funny error while building where I dunno how to fix or where it comes from:

```
brut.androlib.exceptions.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: zip END header not found
	at brut.androlib.apk.ApkInfo.hasManifest(ApkInfo.java:77)
	at brut.androlib.res.ResourcesDecoder.getResTable(ResourcesDecoder.java:57)
	at app.revanced.patcher.data.ResourceContext.decodeResources$revanced_patcher(ResourceContext.kt:68)
	at app.revanced.patcher.Patcher.<init>(Patcher.kt:32)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:213)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: zip END header not found
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:49)
	at brut.androlib.apk.ApkInfo.hasManifest(ApkInfo.java:75)
	... 13 more
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1649)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1657)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1495)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1457)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:253)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:182)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:196)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 16 more
```
@n0k0m3 mybe you can help. I will open a pr so you can see.
